#include<stdio.h>
#include<stdlib.h>
main(){
float soma=0;
float valor=0;
int opcao;
do{
	printf("\n SELECIONE O NUMERO CORRESPONDE DO MENU:\n ");
	printf("\n 1. ______ AGUA");
	printf("\n 2. ______ PIRULITO");
	printf("\n 3. ______ PIRULITO NEON");
	printf("\n 4. ______ SUCO");
	printf("\n 5. ______ COCA LATA");
	printf("\n 6. ______ CERVEJA LATA");
	printf("\n 7. ______ CHOPP COPO");
	printf("\n 8. ______ RED BULL");
	printf("\n 9. ______ CERVEJA LONG");
	printf("\n 10. _____ BALDE COM 5 CERVEJA LONG");
	printf("\n 20. _____ DOSE SMIRNOFF + RED HORSE 400ml");
	printf("\n 30. _____ DOSE SMIRNOFF + RED BULL 400ml");
	printf("\n 40. _____ DOSE ASKOV + RED RORSE 400ml");
	printf("\n 50. _____ DOSE WHISKY + RED RORSE");
	printf("\n 60. _____ DOSE WHISKY JACK + RED BULL 400ml");
	printf("\n 100. ____ COMBO SMIRNOFF + 5 RED BULL");
	printf("\n 101. ____ COMBO SMIRNOFF + 5 SUCO");
	printf("\n 102. ____ COMBO SMIRNOFF + 5 REFRI LATA");
	printf("\n 103. ____ COMBO ABSOLUT + 5 RED BULL");
	printf("\n 104. ____ COMBO RED LABEL + 5 RED BULL");
	printf("\n 105. ____ COMBO JACK PRETO C/MEL + 5 RED BULL");
	printf("\n 106. ____ COMBO JACK MACA + 5 RED BULL");
	printf("\n 200. ____ PASTEL");
	printf("\n 201. ____ BATATA NO CONE\n");
	printf("\n 300.QUAL VALOR PAGO ? ");
	printf("\n 400.SALDO =");
	printf("\n 0.SAIR \n");
	printf("\n NUMERO DO MENU ?");
	scanf("%d",&opcao);
	switch (opcao){
		case 1: printf("\n VALOR DA AGUA ? ");
		scanf("%f", &valor);
		soma=soma+valor;
		break;
		case 2: printf("\n VALOR DO PIRULITO ? ");
		scanf("%f", &valor);
		soma=soma+valor;
		break;
		case 3: printf("\n VALOR DO PIRULITO NEON ? ");
		scanf("%f", &valor);
		soma=soma+valor;
		break;
		case 4: printf("\n VALOR DO SUCO ? ");
		scanf("%f", &valor);
		soma=soma+valor;
		break;
		case 5: printf("\n VALOR DA COCA LATA ? ");
		scanf("%f", &valor);
		soma=soma+valor;
		break;
		case 6: printf("\n VALOR DA CERVEJA LADA ? ");
		scanf("%f", &valor);
		soma=soma+valor;
		break;
		case 7: printf("\n VALOR DO CHOPP COPO ? ");
		scanf("%f", &valor);
		soma=soma+valor;
		break;
		case 8: printf("\n VALOR DO RED BULL ? ");
		scanf("%f", &valor);
		soma=soma+valor;
		break;
		case 9: printf("\n VALOR DA CERVEJA LONG ? ");
		scanf("%f", &valor);
		soma=soma+valor;
		break;
		case 10: printf("\n VALOR DO BALDE COM 5 CERVEJA LONG ? ");
		scanf("%f", &valor);
		soma=soma+valor;
		break;
		case 20: printf("\n VALOR DA DOSE SMIRNOFF + RED HORSE 400ml ? ");
		scanf("%f", &valor);
		soma=soma+valor;
		break;
		case 30: printf("\n VALOR DA DOSE SMIRNOFF + RED BULL 400ml ? ");
		scanf("%f", &valor);
		soma=soma+valor;
		break;
		case 40: printf("\n VALOR DA DOSE ASKOV + RED RORSE 400ml ? ");
		scanf("%f", &valor);
		soma=soma+valor;
		break;
		case 50: printf("\n VALOR DA DOSE WHISKY + RED RORSE ? ");
		scanf("%f", &valor);
		soma=soma+valor;
		break;
		case 60: printf("\n VALOR DA DOSE WHISKY JACK + RED BULL 400ml ? ");
		scanf("%f", &valor);
		soma=soma+valor;
		break;
		case 100: printf("\n VALOR DO COMBO SMIRNOFF + 5 RED BULL ? ");
		scanf("%f", &valor);
		soma=soma+valor;
		break;
		case 101: printf("\n VALOR DO COMBO SMIRNOFF + 5 SUCO ? ");
		scanf("%f", &valor);
		soma=soma+valor;
		break;
		case 102: printf("\n VALOR DO COMBO SMIRNOFF + 5 REFRI LATA ? ");
		scanf("%f", &valor);
		soma=soma+valor;
		break;
		case 103: printf("\n VALOR DO COMBO ABSOLUT + 5 RED BULL ? ");
		scanf("%f", &valor);
		soma=soma+valor;
		break;
		case 104: printf("\n VALOR DO COMBO RED LABEL + 5 RED BULL ? ");
		scanf("%f", &valor);
		soma=soma+valor;
		break;
		case 105: printf("\n VALOR DO COMBO JACK PRETO C/MEL + 5 RED BULL ? ");
		scanf("%f", &valor);
		soma=soma+valor;
		break;
		case 106: printf("\n VALOR DO COMBO JACK MACA + 5 RED BULL ? ");
		scanf("%f", &valor);
		soma=soma+valor;
		break;
		case 200: printf("\n VALOR DO PASTEL ? ");
		scanf("%f", &valor);
		soma=soma+valor;
		break;
		case 201: printf("\n VALOR DA BATATA NO CONE ? ");
		scanf("%f", &valor);
		soma=soma+valor;
		break;
		case 300: printf("\n VALOR PAGO ? ");
		scanf("%f", &valor);
		soma=valor-soma;
		break;
		case 400: printf("\n  ___________________________________________________ SALDO= R$ %.2f \n", soma);
		break;
		default: if(opcao!=0)
		printf("\n OPCAO INVALIDO!\n ");
}
 } while (opcao!=0);
 printf(" FIM DAS OPERACOES. \n\n");
 system("pause");
 return 0;	
}
